services:
  api:
    container_name: api-favorite-products-challenge
    image: api-favorite-producst-challenge-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
      - MONGO_URI=mongodb://root:root@mongodb:27017
    ports:
      - 8000:8000
    networks:
    - nest
    depends_on:
      - mongodb
    command: npm run start:dev
    
  mongodb:
      container_name: mongodb
      image: mongo
      volumes:
        - .mongodb:/data/db
      ports:
        - 27017:27017
      networks:
        - nest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      command: mongod --auth
networks:
    nest:
      driver: bridge
